package org.compiere.model.element;


import org.xendra.annotations.*;
public class ELE_DocumentNo 
{
 	@XendraElement(AD_Element_ID=290,
		ColumnName="DocumentNo",
		EntityType="D",
		Name="Document No",
		PrintName="Document No",
		Description="Document sequence number of the document",
		Help="The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in '<>'.  If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the 'Maintain Sequence' window with the NAME 'DocumentNo_<TableName>', where TableName is the actual NAME of the table (e.g. C_Order).",
		PO_Name="",
		PO_PrintName="",
		PO_Description="",
		PO_Help="",
		Identifier="e3ca6e28-702a-2722-d941-b2072a0de9cb",
		Synchronized="2012-07-11 00:00:00.0")
	public static final String Identifier = "e3ca6e28-702a-2722-d941-b2072a0de9cb";

}
