package org.compiere.model.element;


import org.xendra.annotations.*;
public class ELE_AmtMultiplier 
{
 	@XendraElement(AD_Element_ID=1545,
		ColumnName="AmtMultiplier",
		EntityType="D",
		Name="Multiplier Amount",
		PrintName="Multiplier Amt",
		Description="Multiplier Amount for generating commissions",
		Help="The Multiplier Amount indicates the amount to multiply the total amount generated by this commission run by.",
		PO_Name="",
		PO_PrintName="",
		PO_Description="",
		PO_Help="",
		Identifier="22847cd0-4360-7da7-2be9-defd34416f03",
		Synchronized="2012-07-12 00:00:00.0")
	public static final String Identifier = "22847cd0-4360-7da7-2be9-defd34416f03";

}
