package org.compiere.model.element;


import org.xendra.annotations.*;
public class ELE_ActualLifeTimeValue 
{
 	@XendraElement(AD_Element_ID=153,
		ColumnName="ActualLifeTimeValue",
		EntityType="D",
		Name="Actual Life Time Value",
		PrintName="Actual Life Time Value",
		Description="Actual Life Time Revenue",
		Help="The Actual Life Time Value is the recorded revenue in primary accounting currency generated by the Business Partner.",
		PO_Name="",
		PO_PrintName="",
		PO_Description="",
		PO_Help="",
		Identifier="c8e669f0-6e57-42a8-2fd4-0635228e5d0a",
		Synchronized="2012-07-11 00:00:00.0")
	public static final String Identifier = "c8e669f0-6e57-42a8-2fd4-0635228e5d0a";

}
