package org.compiere.model.element;


import org.xendra.annotations.*;
public class ELE_PotentialLifeTimeValue 
{
 	@XendraElement(AD_Element_ID=515,
		ColumnName="PotentialLifeTimeValue",
		EntityType="D",
		Name="Potential Life Time Value",
		PrintName="Potential Life Time Value",
		Description="Total Revenue expected",
		Help="The Potential Life Time Value is the anticipated revenue in primary accounting currency to be generated by the Business Partner.",
		PO_Name="",
		PO_PrintName="",
		PO_Description="",
		PO_Help="",
		Identifier="1fac643d-32d3-a7bc-de4a-4ad2bf48935f",
		Synchronized="2012-07-11 00:00:00.0")
	public static final String Identifier = "1fac643d-32d3-a7bc-de4a-4ad2bf48935f";

}
