/******************************************************************************
 * Product: Xendra ERP & CRM Smart Business Solution                          *
 * Copyright (C) 1999-2007 ComPiere, Inc. All Rights Reserved.                *
 * This program is free software. you can redistribute it and/or modify it    *
 * under the terms version 2 of the GNU General Public License as published   *
 * by the Free Software Foundation. This program is distributed in the hope   *
 * that it will be useful, but WITHOUT ANY WARRANTY  without even the implied *
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
 * See the GNU General Public License for more details.                       *
 * You should have received a copy of the GNU General Public License along    *
 * with this program, if not, write to the Free Software Foundation, Inc.,    *
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.                     *
 * For the text or an alternative of this public license, you may reach us    *
 * ComPiere, Inc., 2620 Augustine Dr. #245, Santa Clara, CA 95054, USA        *
 * or via info@compiere.org or http://www.compiere.org/license.html           *
 *****************************************************************************/
package org.compiere.model.persistence;

/** Generated Model - DO NOT CHANGE */
import org.compiere.model.*;
import java.util.*;
import java.sql.*;
import java.math.*;
import org.xendra.annotations.*;
import org.compiere.util.*;
/** Generated Model for AD_Note
 *  @author Xendra (generated) 
 *  @version Release 2.00 - $Id: GenerateModel.java 5535 2015-04-28 06:51:56Z xapiens $ */
public class X_AD_Note extends PO
{
/** Standard Constructor
@param ctx context
@param AD_Note_ID id
@param trxName transaction
*/
public X_AD_Note (Properties ctx, int AD_Note_ID, String trxName)
{
super (ctx, AD_Note_ID, trxName);
/** if (AD_Note_ID == 0)
{
setAD_Message_ID (0);
setAD_Note_ID (0);
}
 */
}
/** Load Constructor 
@param ctx context
@param rs result set 
@param trxName transaction
*/
public X_AD_Note (Properties ctx, ResultSet rs, String trxName)
{
super (ctx, rs, trxName);
}
/** AD_Table_ID=389 */
public static int Table_ID=MTable.getTable_ID("AD_Note");

@XendraTrl(Identifier="7301155f-dfd1-de0e-124b-953c3ca35ebb")
public static String es_PE_TAB_Notice_Description="Aviso del Sistema";

@XendraTrl(Identifier="7301155f-dfd1-de0e-124b-953c3ca35ebb")
public static String es_PE_TAB_Notice_Name="Aviso";

@XendraTrl(Identifier="7301155f-dfd1-de0e-124b-953c3ca35ebb")
public static String es_PE_TAB_Notice_Help="La pestaña Aviso provee un método de ver mensajes que son generados por el sistema cuando se ejecutan procesos.";

@XendraTab(Name="Notice",Description="System Notice",
Help="The Notice Tab provides a method of viewing messages that are generated by this system when performing processes.",
AD_Window_ID="88874642-ed87-5062-b8c1-6f5f7bc77fe8",SeqNo=10,TabLevel=0,IsSingleRow=true,
IsInfoTab=false,IsTranslationTab=false,IsReadOnly=false,AD_Column_ID="",HasTree=false,
WhereClause="(AD_User_ID IN (0,@#AD_User_ID@) OR AD_User_ID IS NULL)",OrderByClause="",
CommitWarning="",AD_Process_ID="",AD_ColumnSortOrder_ID="",AD_ColumnSortYesNo_ID="",
IsSortTab=false,Included_Tab_ID="",ReadOnlyLogic="",DisplayLogic="",IsInsertRecord=true,
IsAdvancedTab=false,Parent_Column_ID="",Identifier="7301155f-dfd1-de0e-124b-953c3ca35ebb",
Synchronized="2012-03-17 18:47:08.603")
public static final String TABNAME_Notice="7301155f-dfd1-de0e-124b-953c3ca35ebb";

@XendraTrl(Identifier="fa01df00-f32a-8030-a007-d28669c236c2")
public static String es_PE_TABLE_AD_Note_Name="Aviso";

@XendraTable(Name="Notice",Description="System Notice",Help="",TableName="AD_Note",AccessLevel="7",
AD_Window_ID="88874642-ed87-5062-b8c1-6f5f7bc77fe8",AD_Val_Rule_ID="",IsKey=1,LoadSeq=145,
IsSecurityEnabled=false,IsDeleteable=true,IsHighVolume=true,IsChangeLog=false,IsView=false,
PO_Window_ID="",ID="org.xendra.dictionary",Identifier="fa01df00-f32a-8030-a007-d28669c236c2",
Synchronized="2017-08-16 11:40:31.0")
/** TableName=AD_Note */
public static final String Table_Name="AD_Note";

protected static KeyNamePair Model = new KeyNamePair(Table_ID,"AD_Note");

protected BigDecimal accessLevel = BigDecimal.valueOf(7);
/** AccessLevel
@return 7 - System - Client - Org 
*/
protected int get_AccessLevel()
{
return accessLevel.intValue();
}
/** Load Meta Data
@param ctx context
@return PO Info
*/
protected POInfo initPO (Properties ctx)
{
  if (Table_ID == 0)
    Table_ID = MTable.getTable_ID("AD_Note");
POInfo poi = POInfo.getPOInfo (ctx, Table_ID);
return poi;
}
/** Info
@return info
*/
public String toString()
{
StringBuffer sb = new StringBuffer ("X_AD_Note[").append(get_ID()).append("]");
return sb.toString();
}

/** AD_Message_ID AD_Reference=2c01ec68-5b27-914e-a6ce-60a9b599af92 */
public static final int AD_MESSAGE_ID_AD_Reference_ID=102;
/** Set Message.
@param AD_Message_ID System Message */
public void setAD_Message_ID (int AD_Message_ID)
{
if (AD_Message_ID < 1) throw new IllegalArgumentException ("AD_Message_ID is mandatory.");
set_ValueNoCheck (COLUMNNAME_AD_Message_ID, Integer.valueOf(AD_Message_ID));
}
/** Get Message.
@return System Message */
public int getAD_Message_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_AD_Message_ID);
if (ii == null) return 0;
return ii.intValue();
}
/** Get Record ID/ColumnName
@return ID/ColumnName pair
*/public KeyNamePair getKeyNamePair() 
{
return new KeyNamePair(get_ID(), String.valueOf(getAD_Message_ID()));
}

@XendraTrl(Identifier="a76f5596-2782-2fab-d27f-35133a61a602")
public static String es_PE_FIELD_Notice_Message_Description="Mensaje del sistema";

@XendraTrl(Identifier="a76f5596-2782-2fab-d27f-35133a61a602")
public static String es_PE_FIELD_Notice_Message_Help="Mensajes de información y error.";

@XendraTrl(Identifier="a76f5596-2782-2fab-d27f-35133a61a602")
public static String es_PE_FIELD_Notice_Message_Name="Mensaje";

@XendraField(AD_Column_ID="AD_Message_ID",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=14,IsReadOnly=true,SeqNo=50,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="a76f5596-2782-2fab-d27f-35133a61a602")
public static final String FIELDNAME_Notice_Message="a76f5596-2782-2fab-d27f-35133a61a602";

@XendraTrl(Identifier="e6b8c4c1-9190-73e9-7bdd-ecf561de2d25")
public static String es_PE_COLUMN_AD_Message_ID_Name="Mensaje";

@XendraColumn(AD_Element_ID="22f38416-0f51-247a-d8ef-f2266976960d",ColumnName="AD_Message_ID",
AD_Reference_ID=18,AD_Reference_Value_ID="2c01ec68-5b27-914e-a6ce-60a9b599af92",AD_Val_Rule_ID="",
FieldLength=22,DefaultValue="",IsKey=false,IsInternal=false,IsParent=false,IsMandatory=true,
IsUpdateable=false,ReadOnlyLogic="",IsIdentifier=true,SeqNo=1,IsTranslated=false,Callout="",
VFormat="",ValueMin="",ValueMax="",Version="1",IsSelectionColumn=false,AD_Process_ID="",
IsAlwaysUpdateable=false,ColumnSQL="",IsAllowLogging=false,
Identifier="e6b8c4c1-9190-73e9-7bdd-ecf561de2d25",Synchronized="2017-08-05 16:52:37.0")
/** Column name AD_Message_ID */
public static final String COLUMNNAME_AD_Message_ID = "AD_Message_ID";
/** Set Notice.
@param AD_Note_ID System Notice */
public void setAD_Note_ID (int AD_Note_ID)
{
if (AD_Note_ID < 1) throw new IllegalArgumentException ("AD_Note_ID is mandatory.");
set_ValueNoCheck (COLUMNNAME_AD_Note_ID, Integer.valueOf(AD_Note_ID));
}
/** Get Notice.
@return System Notice */
public int getAD_Note_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_AD_Note_ID);
if (ii == null) return 0;
return ii.intValue();
}

@XendraTrl(Identifier="ff10b04f-0f4b-7002-7d42-79cc8710f63a")
public static String es_PE_FIELD_Notice_Notice_Description="Aviso del sistema";

@XendraTrl(Identifier="ff10b04f-0f4b-7002-7d42-79cc8710f63a")
public static String es_PE_FIELD_Notice_Notice_Name="Aviso";
@XendraField(AD_Column_ID="AD_Note_ID",
IsCentrallyMaintained=true,AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",
IsDisplayed=false,DisplayLogic="",DisplayLength=14,IsReadOnly=true,SeqNo=10,SortNo=1,
IsSameLine=false,IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",
Synchronized="2012-03-17 18:47:14.0",Identifier="ff10b04f-0f4b-7002-7d42-79cc8710f63a")
public static final String FIELDNAME_Notice_Notice="ff10b04f-0f4b-7002-7d42-79cc8710f63a";
/** Column name AD_Note_ID */
public static final String COLUMNNAME_AD_Note_ID = "AD_Note_ID";
/** Set Table.
@param AD_Table_ID Database Table information */
public void setAD_Table_ID (int AD_Table_ID)
{
if (AD_Table_ID <= 0) set_ValueNoCheck (COLUMNNAME_AD_Table_ID, null);
 else 
set_ValueNoCheck (COLUMNNAME_AD_Table_ID, Integer.valueOf(AD_Table_ID));
}
/** Get Table.
@return Database Table information */
public int getAD_Table_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_AD_Table_ID);
if (ii == null) return 0;
return ii.intValue();
}

@XendraTrl(Identifier="d35863b7-6d22-07fa-5cc5-44b3f00a8cc8")
public static String es_PE_FIELD_Notice_Table_Description="Tabla para los campos";

@XendraTrl(Identifier="d35863b7-6d22-07fa-5cc5-44b3f00a8cc8")
public static String es_PE_FIELD_Notice_Table_Help="La Tabla indica una tabla en la que reside un campo ó campos.";

@XendraTrl(Identifier="d35863b7-6d22-07fa-5cc5-44b3f00a8cc8")
public static String es_PE_FIELD_Notice_Table_Name="Tabla";
@XendraField(AD_Column_ID="AD_Table_ID",
IsCentrallyMaintained=true,AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",
IsDisplayed=true,DisplayLogic="",DisplayLength=14,IsReadOnly=true,SeqNo=90,SortNo=0,
IsSameLine=false,IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",
Synchronized="2012-03-17 18:47:14.0",Identifier="d35863b7-6d22-07fa-5cc5-44b3f00a8cc8")
public static final String FIELDNAME_Notice_Table="d35863b7-6d22-07fa-5cc5-44b3f00a8cc8";

@XendraTrl(Identifier="dca2716b-9359-a94e-098a-91c9472cdea1")
public static String es_PE_COLUMN_AD_Table_ID_Name="Tabla";

@XendraColumn(AD_Element_ID="270eeb02-723b-0ecc-7f56-3c67fa71a7f1",ColumnName="AD_Table_ID",
AD_Reference_ID=19,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=22,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=false,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="dca2716b-9359-a94e-098a-91c9472cdea1",
Synchronized="2017-08-05 16:52:37.0")
/** Column name AD_Table_ID */
public static final String COLUMNNAME_AD_Table_ID = "AD_Table_ID";
/** Set User/Contact.
@param AD_User_ID User within the system - Internal or Business Partner Contact */
public void setAD_User_ID (int AD_User_ID)
{
if (AD_User_ID <= 0) set_Value (COLUMNNAME_AD_User_ID, null);
 else 
set_Value (COLUMNNAME_AD_User_ID, Integer.valueOf(AD_User_ID));
}
/** Get User/Contact.
@return User within the system - Internal or Business Partner Contact */
public int getAD_User_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_AD_User_ID);
if (ii == null) return 0;
return ii.intValue();
}

@XendraTrl(Identifier="d7765400-5921-85e9-d014-b45cc6f46054")
public static String es_PE_FIELD_Notice_UserContact_Description="ID de Usuario dentro del sistema";

@XendraTrl(Identifier="d7765400-5921-85e9-d014-b45cc6f46054")
public static String es_PE_FIELD_Notice_UserContact_Help="La ID de usuario identifica un usuario único en el sistema";

@XendraTrl(Identifier="d7765400-5921-85e9-d014-b45cc6f46054")
public static String es_PE_FIELD_Notice_UserContact_Name="Usuario";

@XendraField(AD_Column_ID="AD_User_ID",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=14,IsReadOnly=true,SeqNo=70,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="d7765400-5921-85e9-d014-b45cc6f46054")
public static final String FIELDNAME_Notice_UserContact="d7765400-5921-85e9-d014-b45cc6f46054";

@XendraTrl(Identifier="84fb6f5c-97c4-f7da-b033-77d2f36c0ec0")
public static String es_PE_COLUMN_AD_User_ID_Name="Usuario";

@XendraColumn(AD_Element_ID="abdf8dee-d3cd-73ec-c758-683e907797f4",ColumnName="AD_User_ID",
AD_Reference_ID=19,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=22,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="84fb6f5c-97c4-f7da-b033-77d2f36c0ec0",
Synchronized="2017-08-05 16:52:37.0")
/** Column name AD_User_ID */
public static final String COLUMNNAME_AD_User_ID = "AD_User_ID";
/** Set Workflow Activity.
@param AD_WF_Activity_ID Workflow Activity */
public void setAD_WF_Activity_ID (int AD_WF_Activity_ID)
{
if (AD_WF_Activity_ID <= 0) set_Value (COLUMNNAME_AD_WF_Activity_ID, null);
 else 
set_Value (COLUMNNAME_AD_WF_Activity_ID, Integer.valueOf(AD_WF_Activity_ID));
}
/** Get Workflow Activity.
@return Workflow Activity */
public int getAD_WF_Activity_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_AD_WF_Activity_ID);
if (ii == null) return 0;
return ii.intValue();
}

@XendraTrl(Identifier="3c8d64fa-c02b-8f5b-394b-a8058eac05a3")
public static String es_PE_FIELD_Notice_WorkflowActivity_Description="Actividad de F.T.";

@XendraTrl(Identifier="3c8d64fa-c02b-8f5b-394b-a8058eac05a3")
public static String es_PE_FIELD_Notice_WorkflowActivity_Help="La actividad del flujo de trabajo indica el actual nodo de flujo de trabajo dentro de un proceso del flujo de trabajo.";

@XendraTrl(Identifier="3c8d64fa-c02b-8f5b-394b-a8058eac05a3")
public static String es_PE_FIELD_Notice_WorkflowActivity_Name="Actividad de Flujo de Trabajo";

@XendraField(AD_Column_ID="AD_WF_Activity_ID",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=14,IsReadOnly=true,SeqNo=80,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="3c8d64fa-c02b-8f5b-394b-a8058eac05a3")
public static final String FIELDNAME_Notice_WorkflowActivity="3c8d64fa-c02b-8f5b-394b-a8058eac05a3";

@XendraTrl(Identifier="5d3a5cca-92c4-87b3-419e-b2214c3fdabf")
public static String es_PE_COLUMN_AD_WF_Activity_ID_Name="Actividad de Flujo de Trabajo";

@XendraColumn(AD_Element_ID="80055366-7780-c8b6-b645-12ad4f4a6195",ColumnName="AD_WF_Activity_ID",
AD_Reference_ID=19,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=22,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="5d3a5cca-92c4-87b3-419e-b2214c3fdabf",
Synchronized="2017-08-05 16:52:37.0")
/** Column name AD_WF_Activity_ID */
public static final String COLUMNNAME_AD_WF_Activity_ID = "AD_WF_Activity_ID";
/** Set Description.
@param Description Optional short DESCRIPTION of the record */
public void setDescription (String Description)
{
if (Description != null && Description.length() > 255)
{
log.warning("Length > 255 - truncated");
Description = Description.substring(0,254);
}
set_Value (COLUMNNAME_Description, Description);
}
/** Get Description.
@return Optional short DESCRIPTION of the record */
public String getDescription() 
{
String value = (String)get_Value(COLUMNNAME_Description);
if (value == null)
  return "";
if (value.contains("\""))
  value = value.replaceAll("\"","'");
if (value.contains("\n"))
  value = value.replaceAll("\n"," ");
if (value.contains(";"))
  value = value.replaceAll(";",":");
return value;
}

@XendraTrl(Identifier="3aff0acd-f606-b597-66ac-17272241e147")
public static String es_PE_FIELD_Notice_Description_Description="Observación corta opcional del registro";

@XendraTrl(Identifier="3aff0acd-f606-b597-66ac-17272241e147")
public static String es_PE_FIELD_Notice_Description_Help="Una Observación esta limitada a 255 caracteres";

@XendraTrl(Identifier="3aff0acd-f606-b597-66ac-17272241e147")
public static String es_PE_FIELD_Notice_Description_Name="Observación";

@XendraField(AD_Column_ID="Description",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=60,IsReadOnly=false,SeqNo=130,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="3aff0acd-f606-b597-66ac-17272241e147")
public static final String FIELDNAME_Notice_Description="3aff0acd-f606-b597-66ac-17272241e147";

@XendraTrl(Identifier="e69549ca-4bb6-6080-720b-7173e2d51356")
public static String es_PE_COLUMN_Description_Name="Descripción";

@XendraColumn(AD_Element_ID="2c699aa9-808d-eb67-0fe1-3328890909ca",ColumnName="Description",
AD_Reference_ID=10,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=255,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=true,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="e69549ca-4bb6-6080-720b-7173e2d51356",
Synchronized="2017-08-05 16:52:37.0")
/** Column name Description */
public static final String COLUMNNAME_Description = "Description";
/** Set Identifier.
@param Identifier Identifier */
public void setIdentifier (String Identifier)
{
if (Identifier != null && Identifier.length() > 36)
{
log.warning("Length > 36 - truncated");
Identifier = Identifier.substring(0,35);
}
set_Value (COLUMNNAME_Identifier, Identifier);
}
/** Get Identifier.
@return Identifier */
public String getIdentifier() 
{
String value = (String)get_Value(COLUMNNAME_Identifier);
if (value == null)
  return "";
return value;
}
@XendraTrl(Identifier="11df804d-7814-44db-8d78-96436c826286")
public static String es_PE_COLUMN_Identifier_Name="Identifier";

@XendraColumn(AD_Element_ID="f9dfa544-a995-1afd-baaf-53bbadefbbcb",ColumnName="Identifier",
AD_Reference_ID=10,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=36,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="0",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="11df804d-7814-44db-8d78-96436c826286",
Synchronized="2017-08-05 16:52:37.0")
/** Column name Identifier */
public static final String COLUMNNAME_Identifier = "Identifier";
/** Set Processed.
@param Processed The document has been processed */
public void setProcessed (boolean Processed)
{
set_Value (COLUMNNAME_Processed, Boolean.valueOf(Processed));
}
/** Get Processed.
@return The document has been processed */
public boolean isProcessed() 
{
Object oo = get_Value(COLUMNNAME_Processed);
if (oo != null) 
{
 if (oo instanceof Boolean) return ((Boolean)oo).booleanValue();
 return "Y".equals(oo);
}
return false;
}

@XendraTrl(Identifier="92392e2b-f4db-2032-40d8-ff0583afe38b")
public static String es_PE_FIELD_Notice_Acknowledge_Description="Aviso del sistema de acuse de recibo";

@XendraTrl(Identifier="92392e2b-f4db-2032-40d8-ff0583afe38b")
public static String es_PE_FIELD_Notice_Acknowledge_Help="La casilla de vericaci=F3n Acuse de recibo indica si este aviso no necesita ser conservado.";

@XendraTrl(Identifier="92392e2b-f4db-2032-40d8-ff0583afe38b")
public static String es_PE_FIELD_Notice_Acknowledge_Name="Acuse de recibo";

@XendraField(AD_Column_ID="Processed",IsCentrallyMaintained=false,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=1,IsReadOnly=false,SeqNo=140,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="92392e2b-f4db-2032-40d8-ff0583afe38b")
public static final String FIELDNAME_Notice_Acknowledge="92392e2b-f4db-2032-40d8-ff0583afe38b";

@XendraTrl(Identifier="44759e10-9170-2d67-df9e-036694128d5f")
public static String es_PE_COLUMN_Processed_Name="Procesado";

@XendraColumn(AD_Element_ID="3f7035d2-fa5e-7416-fc0c-e49e43f9e083",ColumnName="Processed",
AD_Reference_ID=20,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=1,DefaultValue="N",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="44759e10-9170-2d67-df9e-036694128d5f",
Synchronized="2017-08-05 16:52:37.0")
/** Column name Processed */
public static final String COLUMNNAME_Processed = "Processed";
/** Set Process Now.
@param Processing Process Now */
public void setProcessing (boolean Processing)
{
set_Value (COLUMNNAME_Processing, Boolean.valueOf(Processing));
}
/** Get Process Now.
@return Process Now */
public boolean isProcessing() 
{
Object oo = get_Value(COLUMNNAME_Processing);
if (oo != null) 
{
 if (oo instanceof Boolean) return ((Boolean)oo).booleanValue();
 return "Y".equals(oo);
}
return false;
}

@XendraTrl(Identifier="2a5ffc91-1162-cea3-f77c-5fa0fdb82b32")
public static String es_PE_FIELD_Notice_ProcessNow_Description="Eliminar todas las Noticias";

@XendraTrl(Identifier="2a5ffc91-1162-cea3-f77c-5fa0fdb82b32")
public static String es_PE_FIELD_Notice_ProcessNow_Name="Eliminar Noticias";

@XendraField(AD_Column_ID="Processing",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=23,IsReadOnly=false,SeqNo=150,SortNo=0,IsSameLine=true,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="2a5ffc91-1162-cea3-f77c-5fa0fdb82b32")
public static final String FIELDNAME_Notice_ProcessNow="2a5ffc91-1162-cea3-f77c-5fa0fdb82b32";

@XendraTrl(Identifier="fbafea70-9c45-f4fc-437d-395c55ab696a")
public static String es_PE_COLUMN_Processing_Name="Procesar Ahora";

@XendraColumn(AD_Element_ID="f2096404-1a98-35ec-09ea-273b3e19b7de",ColumnName="Processing",
AD_Reference_ID=28,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=1,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="9dfe299f-6370-392f-7a2c-3f56fd67b9f5",
IsAlwaysUpdateable=false,ColumnSQL="",IsAllowLogging=false,
Identifier="fbafea70-9c45-f4fc-437d-395c55ab696a",Synchronized="2017-08-05 16:52:37.0")
/** Column name Processing */
public static final String COLUMNNAME_Processing = "Processing";
/** Set Record ID.
@param Record_ID Direct internal record ID */
public void setRecord_ID (int Record_ID)
{
if (Record_ID <= 0) set_ValueNoCheck (COLUMNNAME_Record_ID, null);
 else 
set_ValueNoCheck (COLUMNNAME_Record_ID, Integer.valueOf(Record_ID));
}
/** Get Record ID.
@return Direct internal record ID */
public int getRecord_ID() 
{
Integer ii = (Integer)get_Value(COLUMNNAME_Record_ID);
if (ii == null) return 0;
return ii.intValue();
}

@XendraTrl(Identifier="3d2b1f14-586d-ceb4-1951-c683097037f2")
public static String es_PE_FIELD_Notice_RecordID_Description="Identificador de registro interno";

@XendraTrl(Identifier="3d2b1f14-586d-ceb4-1951-c683097037f2")
public static String es_PE_FIELD_Notice_RecordID_Help="La ID de registro es el identificador único interno de un registro.";

@XendraTrl(Identifier="3d2b1f14-586d-ceb4-1951-c683097037f2")
public static String es_PE_FIELD_Notice_RecordID_Name="ID de Registro";

@XendraField(AD_Column_ID="Record_ID",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=23,IsReadOnly=true,SeqNo=100,SortNo=0,IsSameLine=true,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="3d2b1f14-586d-ceb4-1951-c683097037f2")
public static final String FIELDNAME_Notice_RecordID="3d2b1f14-586d-ceb4-1951-c683097037f2";

@XendraTrl(Identifier="58033d9f-b284-5a43-2ff5-fc51e7d36c8a")
public static String es_PE_COLUMN_Record_ID_Name="ID de Registro";

@XendraColumn(AD_Element_ID="86e36e4b-d1dc-2deb-449d-c1f6769e1603",ColumnName="Record_ID",
AD_Reference_ID=28,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=22,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=false,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="58033d9f-b284-5a43-2ff5-fc51e7d36c8a",
Synchronized="2017-08-05 16:52:37.0")
/** Column name Record_ID */
public static final String COLUMNNAME_Record_ID = "Record_ID";
/** Set Reference.
@param Reference Reference for this record */
public void setReference (String Reference)
{
if (Reference != null && Reference.length() > 60)
{
log.warning("Length > 60 - truncated");
Reference = Reference.substring(0,59);
}
set_Value (COLUMNNAME_Reference, Reference);
}
/** Get Reference.
@return Reference for this record */
public String getReference() 
{
String value = (String)get_Value(COLUMNNAME_Reference);
if (value == null)
  return "";
return value;
}
@XendraTrl(Identifier="c2ef13dd-bbc4-3e1e-6e83-2637a193bbcd")
public static String es_PE_FIELD_Notice_Reference_Description="Referencia para este registro";

@XendraTrl(Identifier="c2ef13dd-bbc4-3e1e-6e83-2637a193bbcd")
public static String es_PE_FIELD_Notice_Reference_Help="La referencia despliega el número del documento fuente";

@XendraTrl(Identifier="c2ef13dd-bbc4-3e1e-6e83-2637a193bbcd")
public static String es_PE_FIELD_Notice_Reference_Name="Referencia";

@XendraField(AD_Column_ID="Reference",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=60,IsReadOnly=true,SeqNo=110,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="c2ef13dd-bbc4-3e1e-6e83-2637a193bbcd")
public static final String FIELDNAME_Notice_Reference="c2ef13dd-bbc4-3e1e-6e83-2637a193bbcd";

@XendraTrl(Identifier="28ebd827-47c7-9bea-7714-eef19e5d48c1")
public static String es_PE_COLUMN_Reference_Name="Referencia";

@XendraColumn(AD_Element_ID="eba276ea-db21-0cfa-29e6-6e0d45ebff99",ColumnName="Reference",
AD_Reference_ID=10,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=60,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=true,SeqNo=2,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="28ebd827-47c7-9bea-7714-eef19e5d48c1",
Synchronized="2017-08-05 16:52:38.0")
/** Column name Reference */
public static final String COLUMNNAME_Reference = "Reference";
/** Set Text Message.
@param TextMsg Text Message */
public void setTextMsg (String TextMsg)
{
set_Value (COLUMNNAME_TextMsg, TextMsg);
}
/** Get Text Message.
@return Text Message */
public String getTextMsg() 
{
String value = (String)get_Value(COLUMNNAME_TextMsg);
if (value == null)
  return "";
return value;
}
@XendraTrl(Identifier="18644844-f05a-8459-eb56-952b20b18432")
public static String es_PE_FIELD_Notice_TextMessage_Description="Mensaje de texto";

@XendraTrl(Identifier="18644844-f05a-8459-eb56-952b20b18432")
public static String es_PE_FIELD_Notice_TextMessage_Name="Mensaje de texto";

@XendraField(AD_Column_ID="TextMsg",IsCentrallyMaintained=true,
AD_Tab_ID="7301155f-dfd1-de0e-124b-953c3ca35ebb",AD_FieldGroup_ID="",IsDisplayed=true,
DisplayLogic="",DisplayLength=60,IsReadOnly=true,SeqNo=120,SortNo=0,IsSameLine=false,
IsHeading=false,IsFieldOnly=false,Included_Tab_ID="",Synchronized="2012-03-17 18:47:14.0",
Identifier="18644844-f05a-8459-eb56-952b20b18432")
public static final String FIELDNAME_Notice_TextMessage="18644844-f05a-8459-eb56-952b20b18432";

@XendraTrl(Identifier="94cc56d5-563d-fa5a-43fc-4797b1b77b06")
public static String es_PE_COLUMN_TextMsg_Name="Mensaje de texto";

@XendraColumn(AD_Element_ID="377bebfe-238a-1c79-c1a9-13afa4448222",ColumnName="TextMsg",
AD_Reference_ID=14,AD_Reference_Value_ID="",AD_Val_Rule_ID="",FieldLength=2000,DefaultValue="",
IsKey=false,IsInternal=false,IsParent=false,IsMandatory=false,IsUpdateable=true,ReadOnlyLogic="",
IsIdentifier=false,SeqNo=0,IsTranslated=false,Callout="",VFormat="",ValueMin="",ValueMax="",
Version="1",IsSelectionColumn=false,AD_Process_ID="",IsAlwaysUpdateable=false,ColumnSQL="",
IsAllowLogging=false,Identifier="94cc56d5-563d-fa5a-43fc-4797b1b77b06",
Synchronized="2017-08-05 16:52:38.0")
/** Column name TextMsg */
public static final String COLUMNNAME_TextMsg = "TextMsg";
}
