//created on: 01/10/2018
package org.xendra.rules.messages

import org.xendra.rules.model.MovementPolicyRequest
import org.xendra.messages.MessageProcessor

dialect "mvel"

// tells the engine that a Sales Policy instance will assume the
// role (semantics) of events 
declare MovementPolicyRequest
    @role( event )
end 

rule "document"
	agenda-group "movement"
when
	$spr : MovementPolicyRequest(processed == false) from entry-point "movement"
	eval($spr.processMovement())
then
	retract ($spr)
end