package org.xendra.printdocument.driver;

public interface PrinterDriver {
	public static final String NL = "nl";
	public static final String beeper = "beeper";
	public static final String line_space_24 = "line_space_24";
	public static final String line_space_30 = "line_space_30";
	public static final String image_mode = "image_mode";
	public static final String hw_init = "hw_init";
	public static final String cd_kick_2 = "cd_kick_2";
	public static final String cd_kick_5 = "cd_kick_5";
	public static final String paper_full_cut = "paper_full_cut";
	public static final String paper_part_cut = "paper_part_cut";
	public static final String txt_normal = "txt_normal";
	public static final String txt_2height = "txt_2height";
	public static final String txt_2width = "txt_2width";
	public static final String txt_4square = "txt_4square";
	public static final String txt_underl_off = "txt_underl_off";
	public static final String txt_underl_on = "txt_underl_on";
	public static final String txt_underl2_on = "txt_underl2_on";
	public static final String txt_bold_off = "txt_bold_off";
	public static final String txt_bold_on = "txt_bold_on";
	public static final String txt_font_a = "txt_font_a";
	public static final String txt_font_b = "txt_font_b";
	public static final String txt_align_lt = "txt_align_lt";
	public static final String txt_align_ct = "txt_align_ct";
	public static final String txt_align_rt = "txt_align_rt";
	public static final String charcode_pc437 = "charcode_pc437";
	public static final String charcode_jis = "charcode_jis";
	public static final String charcode_pc850 = "charcode_pc850";
	public static final String charcode_pc860 = "charcode_pc860";
	public static final String charcode_pc863 = "charcode_pc863";
	public static final String charcode_weu = "charcode_weu";
	public static final String charcode_greek = "charcode_greek";
	public static final String charcode_hebrew = "charcode_hebrew";
	public static final String charcode_pc1252 = "charcode_pc1252";
	public static final String charcode_pc866 = "charcode_pc866";
	public static final String charcode_pc852 = "charcode_pc852";
	public static final String charcode_pc858 = "charcode_pc858";
	public static final String charcode_thai42 = "charcode_thai42";
	public static final String charcode_thai11 = "charcode_thai11";
	public static final String charcode_thai13 = "charcode_thai13";
	public static final String charcode_thai14 = "charcode_thai14";
	public static final String charcode_thai16 = "charcode_thai16";
	public static final String charcode_thai17 = "charcode_thai17";
	public static final String charcode_thai18 = "charcode_thai18";
	public static final String barcode_txt_off = "barcode_txt_off";
	public static final String barcode_txt_abv = "barcode_txt_abv"; 
	public static final String barcode_txt_blw = "barcode_txt_blw"; 
	public static final String barcode_txt_bth = "barcode_txt_bth"; 
	public static final String barcode_font_a = "barcode_font_a"; 
	public static final String barcode_font_b = "barcode_font_b"; 
	public static final String barcode_height = "barcode_height"; 
	public static final String barcode_width = "barcode_width"; 
	public static final String barcode_upc_a = "barcode_upc_a"; 
	public static final String barcode_upc_e = "barcode_upc_e"; 
	public static final String barcode_ean13 = "barcode_ean13"; 
	public static final String barcode_ean8 = "barcode_ean8"; 
	public static final String barcode_code39 = "barcode_code39"; 
	public static final String barcode_itf = "barcode_itf"; 
	public static final String barcode_nw7 = "barcode_nw7"; 
	public static final String pd_n50 = "pd_n50"; 
	public static final String pd_n37 = "pd_n37"; 
	public static final String pd_n25 = "pd_n25"; 
	public static final String pd_n12 = "pd_n12"; 
	public static final String pd_n0 = "pd_n0"; 
	public static final String pd_p50 = "pd_p50"; 
	public static final String pd_p37 = "pd_p37"; 
	public static final String pd_p25 = "pd_p25"; 
	public static final String pd_p12 = "pd_p12"; 	
	public String beeper();
	public String line_space_24(); 
	public String line_space_30();
	public String image_mode();
	public String hw_init();
	public String cd_kick_2(); 
	public String cd_kick_5();
	public String paper_full_cut(); 
	public String paper_part_cut();
	public String txt_normal();
	public String txt_2height();
	public String txt_2width();
	public String txt_4square();
	public String txt_underl_off();
	public String txt_underl_on();
	public String txt_underl2_on();
	public String txt_bold_off();
	public String txt_bold_on();
	public String txt_font_a();
	public String txt_font_b();
	public String txt_align_lt();
	public String txt_align_ct();
	public String txt_align_rt();
	public String charcode_pc437();
	public String charcode_jis();
	public String charcode_pc850();
	public String charcode_pc860();
	public String charcode_pc863();
	public String charcode_weu();
	public String charcode_greek();
	public String charcode_hebrew();
	public String charcode_pc1252();
	public String charcode_pc866();
	public String charcode_pc852();
	public String charcode_pc858();
	public String charcode_thai42();
	public String charcode_thai11();
	public String charcode_thai13();
	public String charcode_thai14();
	public String charcode_thai16();
	public String charcode_thai17();
	public String charcode_thai18();
	public String barcode_txt_off();
	public String barcode_txt_abv();
	public String barcode_txt_blw();
	public String barcode_txt_bth();
	public String barcode_font_a();
	public String barcode_font_b();
	public String barcode_height();
	public String barcode_width();
	public String barcode_upc_a();
	public String barcode_upc_e();
	public String barcode_ean13();
	public String barcode_ean8();
	public String barcode_code39();
	public String barcode_itf();
	public String barcode_nw7();
	public String pd_n50();
	public String pd_n37();
	public String pd_n25();
	public String pd_n12();
	public String pd_n0();
	public String pd_p50();
	public String pd_p37();
	public String pd_p25();
	public String pd_p12();
}

