package org.compiere.model.function;


import org.xendra.annotations.*;
import org.apache.commons.lang.text.StrBuilder;
public class Restoreinvoicedrafted0 
{
 
@XendraFunction(Name="restoreinvoicedrafted",Output="void",Owner="xendra",Language="plpgsql",
Identifier="47eaf0bc-fdf8-a457-6f47-e629e9d5e11f",Arguments="p_pinstance_id numeric",Extension="",
Synchronized="2013-09-29 01:27:28.0")
	public static final String Identifier = "47eaf0bc-fdf8-a457-6f47-e629e9d5e11f";

	public static final String getCode() 
{
 	StrBuilder sb = new StrBuilder();
 	sb.appendln("DECLARE");
	sb.appendln("	--	Parameter");
	sb.appendln("	--	Parameter Variables");
	sb.appendln("	p_AD_Org_ID		NUMERIC(10);");
	sb.appendln("	p_C_Invoice_ID		NUMERIC(10);");
	sb.appendln("	Message			VARCHAR(2000);");
	sb.appendln("	p_IsPaid		VARCHAR(1);");
	sb.appendln("	IS_CASHLINE		VARCHAR(1);");
	sb.appendln("	IS_PAYMENT		VARCHAR(1);");
	sb.appendln("	IS_ALLOCATIONLINE	VARCHAR(1);");
	sb.appendln("	IS_BANKSTATEMENTLINE	VARCHAR(1);");
	sb.appendln("	p			RECORD;");
	sb.appendln("BEGIN");
	sb.appendln("	p_AD_Org_ID := 0;");
	sb.appendln("	p_C_Invoice_ID := 0;");
	sb.appendln("	Message = '';");
	sb.appendln("	IS_CASHLINE = '';");
	sb.appendln("	IS_PAYMENT = '';");
	sb.appendln("	IS_ALLOCATIONLINE = '';");
	sb.appendln("	IS_BANKSTATEMENTLINE = '';");
	sb.appendln("	--	Get Parameters");
	sb.appendln("	FOR p IN");
	sb.appendln("		SELECT");
	sb.appendln("			i.Record_ID,");
	sb.appendln("			i.AD_User_ID,");
	sb.appendln("			par.ParameterName,");
	sb.appendln("			par.P_String,");
	sb.appendln("			par.P_Number,");
	sb.appendln("			par.P_Date");
	sb.appendln("		FROM");
	sb.appendln("			AD_PInstance i,");
	sb.appendln("			AD_PInstance_Para par");
	sb.appendln("		WHERE");
	sb.appendln("			    i.AD_PInstance_ID=p_pinstance_id");
	sb.appendln("			AND i.AD_PInstance_ID=par.AD_PInstance_ID");
	sb.appendln("		ORDER BY");
	sb.appendln("			par.SeqNo");
	sb.appendln("	LOOP");
	sb.appendln("		IF p.ParameterName = 'AD_Org_ID' THEN");
	sb.appendln("			p_AD_Org_ID := p.P_Number;");
	sb.appendln("		ELSIF p.ParameterName = 'C_Invoice_ID' THEN");
	sb.appendln("			p_C_Invoice_ID := p.P_Number;");
	sb.appendln("	 	END IF;");
	sb.appendln("	END LOOP;	--	Get Parameter");
	sb.appendln("	--workflow");
	sb.appendln("	SELECT");
	sb.appendln("		CASE WHEN");
	sb.appendln("			(ispaid='Y' AND c_payment_id>0) OR (c_cashline_id>0) then 'Y' else 'N'");
	sb.appendln("		END");
	sb.appendln("		INTO p_IsPaid");
	sb.appendln("	FROM");
	sb.appendln("		C_Invoice");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	SELECT");
	sb.appendln("		CASE WHEN");
	sb.appendln("			COUNT(*)>0 THEN 'Y' ELSE 'N'");
	sb.appendln("		END");
	sb.appendln("		INTO IS_CASHLINE");
	sb.appendln("	FROM");
	sb.appendln("		C_CASHLINE");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	SELECT");
	sb.appendln("		CASE WHEN");
	sb.appendln("			COUNT(*)>0 THEN 'Y' ELSE 'N'");
	sb.appendln("		END");
	sb.appendln("		INTO IS_PAYMENT");
	sb.appendln("	FROM");
	sb.appendln("		C_PAYMENT");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	SELECT");
	sb.appendln("		CASE WHEN");
	sb.appendln("			COUNT(*)>0 THEN 'Y' ELSE 'N'");
	sb.appendln("		END");
	sb.appendln("		INTO IS_ALLOCATIONLINE");
	sb.appendln("	FROM");
	sb.appendln("		C_ALLOCATIONLINE");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	SELECT");
	sb.appendln("		CASE WHEN");
	sb.appendln("			COUNT(*)>0 THEN 'Y' ELSE 'N'");
	sb.appendln("		END");
	sb.appendln("		INTO IS_BANKSTATEMENTLINE");
	sb.appendln("	FROM");
	sb.appendln("		C_BANKSTATEMENTLINE");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	IF IS_CASHLINE='Y' OR IS_PAYMENT='Y' OR IS_ALLOCATIONLINE='Y' OR IS_BANKSTATEMENTLINE='Y' THEN");
	sb.appendln("		p_IsPaid:='Y';");
	sb.appendln("	ELSE");
	sb.appendln("		p_IsPaid:='N';");
	sb.appendln("	END IF;");
	sb.appendln("	IF p_IsPaid='Y' THEN");
	sb.appendln("		Message:='Invoice '||p_C_Invoice_ID||' is already paid. Delete payment first.';");
	sb.appendln("		UPDATE");
	sb.appendln("			AD_PInstance");
	sb.appendln("		SET");
	sb.appendln("			Updated = now(),");
	sb.appendln("			IsProcessing='N',");
	sb.appendln("			Result = 0,");
	sb.appendln("			ErrorMsg = Message");
	sb.appendln("		WHERE");
	sb.appendln("			AD_PInstance_ID=p_PInstance_ID");
	sb.appendln("		;");
	sb.appendln("		RETURN;");
	sb.appendln("	END IF;");
	sb.appendln("	UPDATE");
	sb.appendln("		C_Invoice");
	sb.appendln("	SET");
	sb.appendln("		DOCSTATUS='DR',");
	sb.appendln("		DOCACTION='CO',");
	sb.appendln("		PROCESSING='N',");
	sb.appendln("		PROCESSED='N',");
	sb.appendln("		POSTED='N'");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID;");
	sb.appendln("	UPDATE");
	sb.appendln("		C_InvoiceLine");
	sb.appendln("	SET");
	sb.appendln("		PROCESSED='N'");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	UPDATE");
	sb.appendln("		C_InvoiceTax");
	sb.appendln("	SET");
	sb.appendln("		PROCESSED='N'");
	sb.appendln("	WHERE");
	sb.appendln("		C_Invoice_ID=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	Message:='Invoice '||p_C_Invoice_ID||' succesfully drafted.';");
	sb.appendln("	UPDATE");
	sb.appendln("		AD_PInstance");
	sb.appendln("	SET");
	sb.appendln("		Updated = now(),");
	sb.appendln("		IsProcessing='N',");
	sb.appendln("		Result=1,");
	sb.appendln("		ErrorMsg=Message");
	sb.appendln("	WHERE");
	sb.appendln("		AD_PInstance_ID=p_PInstance_ID");
	sb.appendln("	;");
	sb.appendln("	--delete account");
	sb.appendln("	DELETE FROM");
	sb.appendln("		fact_acct");
	sb.appendln("	WHERE");
	sb.appendln("		    AD_Table_ID=table_name2id('C_Invoice')");
	sb.appendln("		AND record_id=p_C_Invoice_ID");
	sb.appendln("	;");
	sb.appendln("	--delete account ");
	sb.appendln("END;");
	return sb.toString();
}
	public static final String getComments() 
{
 	StrBuilder sb = new StrBuilder();
 	sb.appendln("@Synchronized=2013-09-29 01:27:28.0");
	sb.appendln("@Identifier=47eaf0bc-fdf8-a457-6f47-e629e9d5e11f");
	return sb.toString();
}
}
