
package pe.gob.sunat.serviceOescondatagate;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillServicePort", targetNamespace = "http://service.sunat.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillServicePort {


    /**
     * 
     * @param fileName
     * @param contentFile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://service.sunat.gob.pe/sendPack")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendPackResponse")
    public String sendPack(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        DataHandler contentFile);

    /**
     * 
     * @param rucComprobante
     * @param serieComprobante
     * @param numeroComprobante
     * @param tipoComprobante
     * @return
     *     returns pe.gob.sunat.service.StatusCdrResponse
     */
    @WebMethod(action = "http://service.sunat.gob.pe/getStatusCdr")
    @WebResult(name = "statusCdr", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.GetStatusCdrResponse")
    public StatusCdrResponse getStatusCdr(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        String numeroComprobante);

    /**
     * 
     * @param ticket
     * @return
     *     returns pe.gob.sunat.service.StatusResponse
     */
    @WebMethod(action = "http://service.sunat.gob.pe/getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.GetStatusResponse")
    public StatusResponse getStatus(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket);

    /**
     * 
     * @param fileName
     * @param contentFile
     * @param requestId
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://service.sunat.gob.pe/sendBill")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendBillResponse")
    public byte[] sendBill(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        DataHandler contentFile,
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId);

    /**
     * 
     * @param fileName
     * @param contentFile
     * @param requestId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://service.sunat.gob.pe/sendSummary")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceOescondatagate.SendSummaryResponse")
    public String sendSummary(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        DataHandler contentFile,
        @WebParam(name = "requestId", targetNamespace = "")
        String requestId);

}
