package org.compiere.model.reference;


import org.xendra.annotations.*;
import org.compiere.model.Reference;

public class REF_EventModelValidator implements Reference 
{
 	@XendraRefItem(Name="Table Before New",
		Value="TBN",
		Description="",
		Identifier="")
	/** Table Before New = TBN */
	public static final String TableBeforeNew = "TBN";
	@XendraRefItem(Name="Table Before Change",
		Value="TBC",
		Description="",
		Identifier="")
	/** Table Before Change = TBC */
	public static final String TableBeforeChange = "TBC";
	@XendraRefItem(Name="Table Before Delete",
		Value="TBD",
		Description="",
		Identifier="")
	/** Table Before Delete = TBD */
	public static final String TableBeforeDelete = "TBD";
	@XendraRefItem(Name="Table After New",
		Value="TAN",
		Description="",
		Identifier="")
	/** Table After New = TAN */
	public static final String TableAfterNew = "TAN";
	@XendraRefItem(Name="Table After Change",
		Value="TAC",
		Description="",
		Identifier="")
	/** Table After Change = TAC */
	public static final String TableAfterChange = "TAC";
	@XendraRefItem(Name="Table After Delete",
		Value="TAD",
		Description="",
		Identifier="")
	/** Table After Delete = TAD */
	public static final String TableAfterDelete = "TAD";
	@XendraRefItem(Name="Document Before Prepare",
		Value="DBPR",
		Description="",
		Identifier="")
	/** Document Before Prepare = DBPR */
	public static final String DocumentBeforePrepare = "DBPR";
	@XendraRefItem(Name="Document Before Void",
		Value="DBVO",
		Description="",
		Identifier="")
	/** Document Before Void = DBVO */
	public static final String DocumentBeforeVoid = "DBVO";
	@XendraRefItem(Name="Document Before Close",
		Value="DBCL",
		Description="",
		Identifier="")
	/** Document Before Close = DBCL */
	public static final String DocumentBeforeClose = "DBCL";
	@XendraRefItem(Name="Document Before Reactivate",
		Value="DBAC",
		Description="",
		Identifier="")
	/** Document Before Reactivate = DBAC */
	public static final String DocumentBeforeReactivate = "DBAC";
	@XendraRefItem(Name="Document Before Reverse Correct",
		Value="DBRC",
		Description="",
		Identifier="")
	/** Document Before Reverse Correct = DBRC */
	public static final String DocumentBeforeReverseCorrect = "DBRC";
	@XendraRefItem(Name="Document Before Reverse Accrual",
		Value="DBRA",
		Description="",
		Identifier="")
	/** Document Before Reverse Accrual = DBRA */
	public static final String DocumentBeforeReverseAccrual = "DBRA";
	@XendraRefItem(Name="Document Before Complete",
		Value="DBCO",
		Description="",
		Identifier="")
	/** Document Before Complete = DBCO */
	public static final String DocumentBeforeComplete = "DBCO";
	@XendraRefItem(Name="Document Before Post",
		Value="DBPO",
		Description="",
		Identifier="")
	/** Document Before Post = DBPO */
	public static final String DocumentBeforePost = "DBPO";
	@XendraRefItem(Name="Document After Prepare",
		Value="DAPR",
		Description="",
		Identifier="")
	/** Document After Prepare = DAPR */
	public static final String DocumentAfterPrepare = "DAPR";
	@XendraRefItem(Name="Document After Void",
		Value="DAVO",
		Description="",
		Identifier="")
	/** Document After Void = DAVO */
	public static final String DocumentAfterVoid = "DAVO";
	@XendraRefItem(Name="Document After Close",
		Value="DACL",
		Description="",
		Identifier="")
	/** Document After Close = DACL */
	public static final String DocumentAfterClose = "DACL";
	@XendraRefItem(Name="Document After Reactivate",
		Value="DAAC",
		Description="",
		Identifier="")
	/** Document After Reactivate = DAAC */
	public static final String DocumentAfterReactivate = "DAAC";
	@XendraRefItem(Name="Document After Reverse Correct",
		Value="DARC",
		Description="",
		Identifier="")
	/** Document After Reverse Correct = DARC */
	public static final String DocumentAfterReverseCorrect = "DARC";
	@XendraRefItem(Name="Document After Reverse Accrual",
		Value="DARA",
		Description="",
		Identifier="")
	/** Document After Reverse Accrual = DARA */
	public static final String DocumentAfterReverseAccrual = "DARA";
	@XendraRefItem(Name="Document After Complete",
		Value="DACO",
		Description="",
		Identifier="")
	/** Document After Complete = DACO */
	public static final String DocumentAfterComplete = "DACO";
	@XendraRefItem(Name="Document After Post",
		Value="DAPO",
		Description="",
		Identifier="")
	/** Document After Post = DAPO */
	public static final String DocumentAfterPost = "DAPO";
	@XendraRef(Name="Event Model Validator",
		AD_Reference_ID="0",
		ValidationType="L",
		Description="",
		Help="",
		VFormat="",
		EntityType="D",
		IsOrderByValue=false,
		Synchronized="2015-07-30 17:57:04.0",
		Extension="",
		Identifier="xendra.getuuid()")
	public static final String Identifier = "xendra.getuuid()";

}
