package org.compiere.model.reference;


import org.xendra.annotations.*;
import org.compiere.model.Reference;

public class REF_C_DocTypeDocBaseType implements Reference 
{
 	@XendraRefItem(Name="Purchase Order",
		Value="POO",
		Description="",
		Identifier="5f3a4e80-7224-e3fa-70ad-55a52221e42a")
	/** Purchase Order = POO */
	public static final String PurchaseOrder = "POO";
	@XendraRefItem(Name="Purchase Requisition",
		Value="POR",
		Description="",
		Identifier="b13b4932-b9dd-eb72-3d17-9e4a43df1929")
	/** Purchase Requisition = POR */
	public static final String PurchaseRequisition = "POR";
	@XendraRefItem(Name="Match Invoice",
		Value="MXI",
		Description="",
		Identifier="27878161-42b0-b6f0-e6c2-851743af7095")
	/** Match Invoice = MXI */
	public static final String MatchInvoice = "MXI";
	@XendraRefItem(Name="Material Production",
		Value="MMP",
		Description="",
		Identifier="817ec452-019e-3c72-a52a-0c3d5bd8fe2b")
	/** Material Production = MMP */
	public static final String MaterialProduction = "MMP";
	@XendraRefItem(Name="Project Issue",
		Value="PJI",
		Description="",
		Identifier="354829c0-1d37-e9d6-1f58-a653707e4ead")
	/** Project Issue = PJI */
	public static final String ProjectIssue = "PJI";
	@XendraRefItem(Name="AP Credit Memo",
		Value="APC",
		Description="",
		Identifier="d244e199-911f-e9f6-9afb-18e980c43cf0")
	/** AP Credit Memo = APC */
	public static final String APCreditMemo = "APC";
	@XendraRefItem(Name="AR Credit Memo",
		Value="ARC",
		Description="",
		Identifier="c968bf98-9201-4920-fca7-f7e4efb4dcd8")
	/** AR Credit Memo = ARC */
	public static final String ARCreditMemo = "ARC";
	@XendraRefItem(Name="GL Journal",
		Value="GLJ",
		Description="",
		Identifier="75c4704d-9258-a88c-bce7-ae9a94d2b9f9")
	/** GL Journal = GLJ */
	public static final String GLJournal = "GLJ";
	@XendraRefItem(Name="GL Document",
		Value="GLD",
		Description="",
		Identifier="84ca4202-f874-1338-26cd-d018c5488c16")
	/** GL Document = GLD */
	public static final String GLDocument = "GLD";
	@XendraRefItem(Name="AP Invoice",
		Value="API",
		Description="",
		Identifier="e302de97-f4e7-af00-a264-74c1107395b5")
	/** AP Invoice = API */
	public static final String APInvoice = "API";
	@XendraRefItem(Name="Match PO",
		Value="MXP",
		Description="",
		Identifier="c4815b85-f459-a8ed-8209-b6d4995dae43")
	/** Match PO = MXP */
	public static final String MatchPO = "MXP";
	@XendraRefItem(Name="Cash Journal",
		Value="CMC",
		Description="",
		Identifier="1291689c-d4df-921f-038b-e6af29f38223")
	/** Cash Journal = CMC */
	public static final String CashJournal = "CMC";
	@XendraRefItem(Name="Bill Of Exchange",
		Value="BOE",
		Description="",
		Identifier="79692987-ec25-6eec-cebb-46db7b359f63")
	/** Bill Of Exchange = BOE */
	public static final String BillOfExchange = "BOE";
	@XendraRefItem(Name="Personal fee ship",
		Value="FPS",
		Description="",
		Identifier="bde73465-dbb2-1551-9a7d-793c2f35a237")
	/** Personal fee ship = FPS */
	public static final String PersonalFeeShip = "FPS";
	@XendraRefItem(Name="Material Return Of Vendor",
		Value="MRV",
		Description="",
		Identifier="a580276c-396e-c317-6b6c-7c6c0f43d352")
	/** Material Return Of Vendor = MRV */
	public static final String MaterialReturnOfVendor = "MRV";
	@XendraRefItem(Name="Material Return Of Customer",
		Value="MRC",
		Description="",
		Identifier="9e98ffb4-a4cf-d3df-cd72-0841942a2ab5")
	/** Material Return Of Customer = MRC */
	public static final String MaterialReturnOfCustomer = "MRC";
	@XendraRefItem(Name="AP Payment",
		Value="APP",
		Description="",
		Identifier="804dd837-8ede-a2b0-c24e-e9c7ff19e1c6")
	/** AP Payment = APP */
	public static final String APPayment = "APP";
	@XendraRefItem(Name="AR Invoice",
		Value="ARI",
		Description="",
		Identifier="8d58c8df-d9eb-fd6d-ad47-9efc9e073ff8")
	/** AR Invoice = ARI */
	public static final String ARInvoice = "ARI";
	@XendraRefItem(Name="AR Receipt",
		Value="ARR",
		Description="",
		Identifier="27839356-61e4-7f45-000b-8f8787a8ef0f")
	/** AR Receipt = ARR */
	public static final String ARReceipt = "ARR";
	@XendraRefItem(Name="Sales Order",
		Value="SOO",
		Description="",
		Identifier="a3fa345f-ee27-b649-59cb-baa60102d944")
	/** Sales Order = SOO */
	public static final String SalesOrder = "SOO";
	@XendraRefItem(Name="AR Pro Forma Invoice",
		Value="ARF",
		Description="",
		Identifier="1b95ec10-2517-54cf-7610-83575123d453")
	/** AR Pro Forma Invoice = ARF */
	public static final String ARProFormaInvoice = "ARF";
	@XendraRefItem(Name="Material Delivery",
		Value="MMS",
		Description="",
		Identifier="bef63ccb-14b6-57c8-ba63-42ac1efb4cde")
	/** Material Delivery = MMS */
	public static final String MaterialDelivery = "MMS";
	@XendraRefItem(Name="Material Receipt",
		Value="MMR",
		Description="",
		Identifier="7198ad18-64f5-79f7-7dec-e446633b18a8")
	/** Material Receipt = MMR */
	public static final String MaterialReceipt = "MMR";
	@XendraRefItem(Name="Payment Allocation",
		Value="CMA",
		Description="",
		Identifier="5d82cd0c-3b7f-028b-1cd5-11ee7cd146fe")
	/** Payment Allocation = CMA */
	public static final String PaymentAllocation = "CMA";
	@XendraRefItem(Name="Material Physical Inventory",
		Value="MMI",
		Description="",
		Identifier="ef00a85f-7d01-2090-33fc-a702b41a90fc")
	/** Material Physical Inventory = MMI */
	public static final String MaterialPhysicalInventory = "MMI";
	@XendraRefItem(Name="Retention",
		Value="RET",
		Description="",
		Identifier="20bc98d7-45d6-189f-e6ac-4fbef2e9d579")
	/** Retention = RET */
	public static final String Retention = "RET";
	@XendraRefItem(Name="AR Invoice Free Transfer",
		Value="ART",
		Description="",
		Identifier="7a9a9264-ffe2-46e4-bb01-4193a24608be")
	/** AR Invoice Free Transfer = ART */
	public static final String ARInvoiceFreeTransfer = "ART";
	@XendraRefItem(Name="Declaration Customs Value",
		Value="DCV",
		Description="",
		Identifier="")
	/** Declaration Customs Value = DCV */
	public static final String DeclarationCustomsValue = "DCV";
	@XendraRefItem(Name="AP Credit Memo Discount",
		Value="APD",
		Description="",
		Identifier="")
	/** AP Credit Memo Discount = APD */
	public static final String APCreditMemoDiscount = "APD";
	@XendraRefItem(Name="Material Movement",
		Value="MMM",
		Description="",
		Identifier="94ea4995-912f-048d-e1f1-c771a580577c")
	/** Material Movement = MMM */
	public static final String MaterialMovement = "MMM";
	@XendraRefItem(Name="Bank Account Transfer",
		Value="BAT",
		Description="",
		Identifier="d7144453-6497-81bd-8fda-67c229e20713")
	/** Bank Account Transfer = BAT */
	public static final String BankAccountTransfer = "BAT";
	@XendraRefItem(Name="Bank Statement",
		Value="CMB",
		Description="",
		Identifier="8f57cf9a-6f57-74e1-f9f7-061759848fc3")
	/** Bank Statement = CMB */
	public static final String BankStatement = "CMB";
	@XendraRefItem(Name="Withholding",
		Value="WIT",
		Description="",
		Identifier="1267eaf9-8946-4e0e-b37f-4190494c8640")
	/** Withholding = WIT */
	public static final String Withholding = "WIT";
	@XendraRefItem(Name="Material Production reversed",
		Value="MPR",
		Description="",
		Identifier="dce5392b-da6e-4730-8df0-cb44eb3c1eff")
	/** Material Production reversed = MPR */
	public static final String MaterialProductionReversed = "MPR";
	@XendraRefItem(Name="Payroll",
		Value="HRP",
		Description="",
		Identifier="cebe0efa-73ab-497d-93c7-4eff2311bec4")
	/** Payroll = HRP */
	public static final String Payroll = "HRP";
	@XendraRefItem(Name="AP Debit",
		Value="APB",
		Description="",
		Identifier="20bd8a1e-1d88-4df3-808e-30531c11ca29")
	/** AP Debit = APB */
	public static final String APDebit = "APB";
	@XendraRefItem(Name="Material Adjust",
		Value="MMA",
		Description="",
		Identifier="bc2626e5-c959-42f0-bc42-1ace4a90949a")
	/** Material Adjust = MMA */
	public static final String MaterialAdjust = "MMA";
	@XendraRef(Name="C_DocType DocBaseType",
		AD_Reference_ID="0",
		ValidationType="L",
		Description="Base Document Types",
		Help="",
		VFormat="LLL",
		EntityType="D",
		IsOrderByValue=false,
		Synchronized="2017-10-10 17:03:47.204",
		Extension="",
		Identifier="c1999318-834d-4c66-5345-371ffe3c1f06")
	public static final String Identifier = "c1999318-834d-4c66-5345-371ffe3c1f06";

}
